package com.example.myapplication.youtubeVD.pojo

import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "mealstickerInformation")
data class Meal(
    val dateModified: Any,
    @PrimaryKey
//    val idMeal: String,
//    val strArea: String?,
//    val strCategory: String,
//    val strCreativeCommonsConfirmed: Any?,
//    val strDrinkAlternate: Any?,
//    val strImageSource: Any?,
//    val strIngredient1: String?,
//    val strIngredient10: String?,
//    val strIngredient11: String?,
//    val strIngredient12: String?,
//    val strIngredient13: String?,
//    val strIngredient14: String?,
//    val strIngredient15: String?,
//    val strIngredient16: String?,
//    val strIngredient17: String?,
//    val strIngredient18: String?,
//    val strIngredient19: String?,
//    val strIngredient2: String?,
//    val strIngredient20: String?,
//    val strMeasure18: String?,
//    val strMeasure19: String?,
//    val strMeasure2: String?,
//    val strMeasure20: String?,
//    val strMeasure3: String?,
//    val strMeasure4: String?,
//    val strMeasure5: String?,
//    val strMeasure6: String?,
//    val strMeasure7: String?,
//    val strMeasure8: String?,
//    val strMeasure9: String?,
//    val strSource: String?,
//    val strTags: Any?,
//    val strYoutube: String?

    val idMeal: String,
    val strArea: String,
    val strCategory: String,
    val strCreativeCommonsConfirmed: Any,
    val strDrinkAlternate: Any,
    val strImageSource: Any,
    val strIngredient1: String,
    val strIngredient10: String,
    val strIngredient11: String,
    val strIngredient12: String,
    val strIngredient13: String,
    val strIngredient14: String,
    val strIngredient15: String,
    val strIngredient16: String,
    val strIngredient17: String,
    val strIngredient18: String,
    val strIngredient19: String,
    val strIngredient2: String,
    val strIngredient20: String,
    val strMeasure18: String,
    val strMeasure19: String,
    val strMeasure2: String,
    val strMeasure20: String,
    val strMeasure3: String,
    val strMeasure4: String,
    val strMeasure5: String,
    val strMeasure6: String,
    val strMeasure7: String,
    val strMeasure8: String,
    val strMeasure9: String,
    val strSource: String,
    val strTags: Any,
    val strYoutube: String
)